/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as NovoIndexRouteImport } from './routes/novo.index'
import { Route as NovoTypeIdRouteImport } from './routes/novo.$typeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoIndexRoute = NovoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovoRoute,
} as any)
const NovoTypeIdRoute = NovoTypeIdRouteImport.update({
  id: '/$typeId',
  path: '/$typeId',
  getParentRoute: () => NovoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/novo': typeof NovoRouteWithChildren
  '/novo/$typeId': typeof NovoTypeIdRoute
  '/novo/': typeof NovoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/novo/$typeId': typeof NovoTypeIdRoute
  '/novo': typeof NovoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/novo': typeof NovoRouteWithChildren
  '/novo/$typeId': typeof NovoTypeIdRoute
  '/novo/': typeof NovoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/novo' | '/novo/$typeId' | '/novo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/novo/$typeId' | '/novo'
  id: '__root__' | '/' | '/novo' | '/novo/$typeId' | '/novo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NovoRoute: typeof NovoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo/': {
      id: '/novo/'
      path: '/'
      fullPath: '/novo/'
      preLoaderRoute: typeof NovoIndexRouteImport
      parentRoute: typeof NovoRoute
    }
    '/novo/$typeId': {
      id: '/novo/$typeId'
      path: '/$typeId'
      fullPath: '/novo/$typeId'
      preLoaderRoute: typeof NovoTypeIdRouteImport
      parentRoute: typeof NovoRoute
    }
  }
}

interface NovoRouteChildren {
  NovoTypeIdRoute: typeof NovoTypeIdRoute
  NovoIndexRoute: typeof NovoIndexRoute
}

const NovoRouteChildren: NovoRouteChildren = {
  NovoTypeIdRoute: NovoTypeIdRoute,
  NovoIndexRoute: NovoIndexRoute,
}

const NovoRouteWithChildren = NovoRoute._addFileChildren(NovoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NovoRoute: NovoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
